### PR TITLE
Fixed bugs to run PR2 couter balance adjustment on Indigo

### PR DESCRIPTION
**Pull request by knorth55**
I fixed several bugs to run PR2 counter balance adjustment on Indigo
- add message_generation and message_runtime
- add srvs
- add python setup.py
- add install in pr2_counterbalance_check

cc. @YutoUchimi

### CODE REVIEW

**Comment by knorth55** [comment]
Before left arm adjustment (right arm is already adjusted)
IMG_4122


After left arm adjustment
IMG_4128
IMG_4130

**Review by v4hn — CHANGES_REQUESTED** [review]
Please remove the pyc file you added by accident.

**Comment by knorth55** [comment]
I updated to remove `*.pyc`

**Review by v4hn — APPROVED** [review]

**Comment by knorth55** [comment]
@k-okada i don't know why but travis test does not start.
can you restart the travis test?

**Comment by knorth55** [comment]
@k-okada kindly ping

**Comment by knorth55** [comment]
travis passed :100:

**Pull request merged**
