### PR TITLE
Fix String IO and numpy byte error in Python3

### PR DESCRIPTION
**Pull request by mqcmd196**

### CODE REVIEW

**Comment by mqcmd196** [comment]
We confirmed @708yamaguchi 's patch works well with PR1040 too.

**Comment by 708yamaguchi** [comment]
Thanks for the confirmation!

**Comment by mqcmd196** [comment]
@k-okada 
Please review and release it if you have time.

**Review by v4hn — APPROVED** [review]
Thank you. Looks plausible to me.

**Pull request merged**
